### ISSUE TITLE
0.2.1 Build Failure

### ISSUE THREAD

**Issue by githububub** [sabotage-linux/netbsd-curses#27]
>libcurses/slk.c: In function '__slk_set':
libcurses/slk.c:488:10: error: implicit declaration of function 'wcwidth' [-Werror=implicit-function-declaration]
   len += wcwidth(wc);

Last known successful build was 22acb33 so something between then and now may be the culprit.

**Comment by githububub** [comment]
Build failure on Arch due to changes in commit 9423d341d6d583d23427abda09c9846e070c45e0.

**Comment by rofl0r** [comment]
thanks for the report. can you confirm if the commit i just pushed fixes it ?

**Comment by githububub** [comment]
Commit a3a67237f7b9586a8e87d34190ec1d57b9cba983:

>libcurses/slk.c: In function '__slk_set':
libcurses/slk.c:481:10: error: implicit declaration of function 'wcwidth' [-Werror=implicit-function-declaration]
   len += wcwidth(wc);

**Comment by rofl0r** [comment]
wasn't my intention to close this. is the issue now fixed ?

**Comment by githububub** [comment]
No build warnings. No build errors. Rebuilt nano against 194ddef273935a1dc96f0c2588b924c2e7b96c28. No nano build warnings. No nano build errors. nano operates as expected. Issue appears to be resolved. Thank you!

**Comment by rofl0r** [comment]
cool, thanks.
